# Generated by Django 4.0 on 2021-12-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='cavalaria',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='combustivel',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='torque',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
