# Generated by Django 4.0 on 2021-12-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carros_cavalaria_carros_combustivel_carros_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='cavalaria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carros',
            name='torque',
            field=models.IntegerField(),
        ),
    ]
